system_settings:
    data_dir: '/tmp/dataset/'
    save_dir: '/content/drive/My Drive/MusicCaptioning/Walter/checkpoints/'
    sys_path: '/content/drive/My Drive/MusicCaptioning/Walter/'
    model_lib_path: '/content/drive/My Drive/MusicCaptioning/Walter/models/'
    metrics_path: '/content/drive/My Drive/MusicCaptioning/Walter/metrics/'
    checkpoint_path: '/content/drive/MyDrive/MusicCaptioning/Nikhil/checkpoints/model_Wavegram_Logmel_Cnn14.pth'

hyperparameters:
    split: 'train/val'
    epochs: 100
    batch_size: 64
    random_seed: 7643
    lr: 0.07

network:
    model: "PANN"
    fine_tune: True
    get_metrics: True

weights:
    pretrained: True
    retrieval_method: from_library
    weight_file: None