system_settings:
    data_dir: '/tmp/dataset/'
    save_dir: '/content/drive/My Drive/MusicCaptioning/Walter/checkpoints/'
    sys_path: '/content/drive/My Drive/MusicCaptioning/Walter/'
    model_lib_path: '/content/drive/My Drive/MusicCaptioning/Walter/models/'
    metrics_path: '/content/drive/My Drive/MusicCaptioning/Walter/metrics/'
    checkpoint_path: '/content/drive/My Drive/MusicCaptioning/Walter/checkpoints/seed_7643_20221204000000/model_5.pth'

hyperparameters:
    split: 'train/val'
    epochs: 100
    batch_size: 256
    random_seed: 7643
    lr: 0.07

network:
    model: "ResNet"
    fine_tune: True
    get_metrics: True

weights:
    pretrained: True
    retrieval_method: from_library
    weight_file: None