system_settings:
    data_dir: '/home/jupyter/data/'
    save_dir: '/home/jupyter/checkpoints/'
    sys_path: '/home/jupyter/music'
    model_lib_path: '/home/jupyter/music/models/'

hyperparameters:
    epochs: 100
    batch_size: 16
    random_seed: 7643

network:
    model: ResNet
    get_feat_vec: True
    embedding_layer: avgpool

weights:
    pretrained: True
    retrieval_method: from_library
    weight_file: None