hyperparameters:
  data_dir: '/home/nikhilrk/MusicCaptioning/MusicCaptioning/clotho-dataset/data'
  split: 'dev'
  epochs: 1000
  batch_size: 16


network:
  model: ResNet
  get_feat_vec: True
  embedding_layer: avgpool

weights:
  pretrained: True
  retrieval_method: from_library
  weight_file: None