hyperparameters:
  data_dir: 'C:/Users/wabec/MSA/7643/Project/MusicCaptioning/dataset/'
  split: 'dev'
  epochs: 1000
  batch_size: 16
  vocab_file: 'C:/Users/wabec/MSA/7643/Project/MusicCaptioning/vocab/'
  save_dir: 'C:/Users/wabec/MSA/7643/Project/MusicCaptioning/checkpoint/'


network:
  model: ResNet
  get_feat_vec: True
  embedding_layer: avgpool

weights:
  pretrained: True
  retrieval_method: from_library
  weight_file: None