system_settings:
    data_dir: '/home/jupyter/data/'
    save_dir: '/home/jupyter/checkpoints/ViT'
    sys_path: '/home/jupyter/music'
    model_lib_path: '/home/jupyter/music/models/'

hyperparameters:
    split: 'dev'
    epochs: 100
    batch_size: 16
    random_seed: 7643

network:
    model: "ViT"

weights:
    pretrained: True
    retrieval_method: from_library
    weight_file: None